packages:
  - 'helper'
  - 'devHelper'
  - 'ssr'
  - 'tag'
  - 'ftags'
  - 'examples'
  - 'jsx-runtime'
  - 'lithentDocs'
  - 'createLithent'
  - 'createLithent/express'
  - 'createLithent/basic'
  - 'packages/hmrParser'
  - 'packages/lithentVite'
  - 'packages/lithentMdx'
  - 'packages/lithentTemplateVite'
  - 'packages/lithentTemplateParser'
